### ISSUE TITLE
Cluster todo's

### ISSUE THREAD

**Issue by buroa** [buroa/k8s-gitops#208]
- [ ] feat: Litmus https://docs.litmuschaos.io/
- [ ] feat: Databases for postgres & redis
- [ ] feat: External secrets
- [ ] chore: Task files
